language: go

go:
  - 1.7.x
  - master

go_import_path: "github.com/jack482653/pttCrawler"

install:
  - make get-deps

script:
  - go test ./ptt -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
